### ISSUE TITLE
SETMUMPS.COM does not allow for drive selection

### ISSUE THREAD

**Issue by atariquest** [MockbaTheBorg/MicroMumps#1]
Using RunCPM or Apple II Softcard. 

SETMUMPS.COM prompts "Enter drive of the MUMPS.COM to change:". I have MUMPS.COM on both drives A: and B: It does not matter which drive letter I enter the prompt will be asked again resulting in an infinite prompt loop. I have tried different letter combinations such as "A", "A:", "a", "a:"., etc.

**Comment by atariquest** [comment]
![Capture](https://user-images.githubusercontent.com/109930359/180675579-2d5fdd48-1029-4a74-a18e-8bf5f5c9dd3d.JPG)

**Comment by atariquest** [comment]
I figure out the issue. The file SETMUMPS.ASM has a constant for MumpsFCB. I commented it out and uncommented the references to MumpsFCB in the data section like this:
MumpsFCB:	db    0
		db 'MUMPS   COM'
		ds    24
It works now.

**Comment by MockbaTheBorg** [comment]
Good catch. I will apply this fix.
